# Generated by Django 5.0.6 on 2024-07-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_city_image_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='info',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
